name: Run tests

on: [push, pull_request]

jobs:  
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Clone supercharge website repository
      uses: actions/checkout@master
      with:
        name: tosunthex/CoinGecko_NodeJS_test
        ref: CoinGecko_NodeJs
        node-version: 14

    - run: npm install mocha
    - run: npm install chai
    - run: node_modules/mocha/bin/mocha test/CoinGecko.tests.js
